[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd packages/flare-kinetic-liquidator && npm ci --only=production --ignore-scripts"]

[phases.build]
cmds = [
  "cd packages/flare-kinetic-liquidator && npm install",
  "cd packages/flare-kinetic-liquidator && npx hardhat compile",
  "cd packages/flare-kinetic-liquidator && npx tsc -p tsconfig.json",
  "ls -la packages/flare-kinetic-liquidator/dist || echo 'dist folder not found'"
]

[start]
cmd = "cd packages/flare-kinetic-liquidator && node dist/src/main.js"

