[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cwd = "packages/flare-kinetic-liquidator"
cmds = ["npm install"]

[phases.build]
cwd = "packages/flare-kinetic-liquidator"
cmds = [
  "npx hardhat compile",
  "npm run build"
]

[start]
cmd = "node dist/main.js"
cwd = "packages/flare-kinetic-liquidator"

